logbook.write.level: INFO
logbook.format.style: json
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**
